import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,doc,setDoc,getDoc,collection,query,where,getDocs,limit,onSnapshot,addDoc,deleteDoc,serverTimestamp,orderBy} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);let me=null,active=null,stopMessages=null,stopThreads=null,users=new Map(),threads=[];
const status=t=>$('status').textContent=t;const feedback=t=>$('authFeedback').textContent=t;
function clean(s){return String(s||'').trim()};function initials(s){return clean(s).slice(0,1).toUpperCase()||'?'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function pair(a,b){return [a,b].sort().join('_')}
$('googleLogin').onclick=async()=>{feedback('Opening Google sign-in…');try{await signInWithPopup(auth,provider)}catch(e){if(e.code==='auth/popup-blocked'){try{await signInWithRedirect(auth,provider);return}catch(x){feedback(x.message);return}}feedback(e.message)}};
getRedirectResult(auth).catch(e=>feedback(e.message));
$('logoutBtn').onclick=()=>signOut(auth);
async function upsertMe(u){const ref=doc(db,'users',u.uid),snapshot=await getDoc(ref);if(!snapshot.exists()){await setDoc(ref,{displayName:u.displayName||'User',email:u.email||'',photoURL:u.photoURL||'',createdAt:serverTimestamp()})}else{await setDoc(ref,{displayName:u.displayName||'User',photoURL:u.photoURL||''},{merge:true})}}
onAuthStateChanged(auth,async u=>{if(stopMessages){stopMessages();stopMessages=null}if(stopThreads){stopThreads();stopThreads=null}active=null;threads=[];me=u;$('authPage').classList.toggle('hidden',!!u);$('appShell').classList.toggle('hidden',!u);$('appShell').classList.remove('chat-open');$('chatView').classList.add('hidden');$('chatWelcome').classList.remove('hidden');if(!u)return;try{await upsertMe(u);$('sideName').textContent=u.displayName||'User';$('sideHandle').textContent=u.email||'';$('sideAvatar').textContent=initials(u.displayName);watchThreads()}catch(e){feedback(e.message);alert('Could not load account: '+e.message)}});
function watchThreads(){stopThreads=onSnapshot(query(collection(db,'threads'),where('members','array-contains',me.uid)),snap=>{threads=snap.docs.map(d=>({id:d.id,...d.data()}));if(!$('searchInput').value.trim())renderThreads()},e=>status('Could not load chats: '+e.message))}
function makePersonButton(u,click,preview='Start private chat'){const b=el('button','conversation');b.type='button';const a=el('div','avatar',initials(u.displayName));const body=el('div','conversation-body');body.append(el('strong',null,u.displayName||'User'),el('small',null,preview));b.append(a,body);b.onclick=click;return b}
async function getUser(uid){if(users.has(uid))return users.get(uid);const snap=await getDoc(doc(db,'users',uid));const u=snap.exists()?{uid,...snap.data()}:{uid,displayName:'User'};users.set(uid,u);return u}
async function renderThreads(){const nav=$('conversationList');nav.replaceChildren();$('listTitle').textContent='Your conversations';$('allChatsBtn').classList.add('hidden');$('emptyList').textContent='No chats yet. Tap “New personal chat” to start.';$('emptyList').classList.toggle('hidden',threads.length>0);for(const t of threads){const other=t.members.find(id=>id!==me.uid);if(!other)continue;const u=await getUser(other);nav.append(makePersonButton(u,()=>openChat(t.id,u),'Private conversation'))}}
async function searchPeople(term){const nav=$('conversationList');nav.replaceChildren();$('listTitle').textContent='Find people';$('allChatsBtn').classList.remove('hidden');$('emptyList').classList.add('hidden');const q=clean(term).toLowerCase();if(!q){nav.append(el('p','empty-list','Type a name or email to search.'));return}try{const snap=await getDocs(query(collection(db,'users'),limit(100)));const results=snap.docs.map(d=>({uid:d.id,...d.data()})).filter(u=>u.uid!==me.uid&&((u.displayName||'').toLowerCase().includes(q)||(u.email||'').toLowerCase().includes(q))).slice(0,30);if(!results.length)nav.append(el('p','empty-list','No matching users found.'));for(const u of results)nav.append(makePersonButton(u,()=>startChat(u),u.email||'Google account'))}catch(e){nav.append(el('p','empty-list','Search failed: '+e.message))}}
$('newChatBtn').onclick=$('mobileNewChat').onclick=()=>{$('searchInput').value='';searchPeople('');$('searchInput').focus()};$('allChatsBtn').onclick=()=>{$('searchInput').value='';renderThreads()};let searchTimer;$('searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{$('searchInput').value.trim()?searchPeople($('searchInput').value):renderThreads()},250)};
async function startChat(u){try{const id=pair(me.uid,u.uid);await setDoc(doc(db,'threads',id),{members:[me.uid,u.uid].sort(),updatedAt:serverTimestamp()},{merge:true});openChat(id,u)}catch(e){alert('Could not create chat: '+e.message)}}
function openChat(id,u){if(stopMessages)stopMessages();active={id,other:u};$('chatWelcome').classList.add('hidden');$('chatView').classList.remove('hidden');$('appShell').classList.add('chat-open');$('chatName').textContent=u.displayName||'User';$('chatAvatar').textContent=initials(u.displayName);$('messages').replaceChildren();status('Loading messages…');stopMessages=onSnapshot(query(collection(db,'threads',id,'messages'),orderBy('createdAt','desc'),limit(300)),snap=>{const container=$('messages');container.replaceChildren();const arr=snap.docs.slice().reverse();for(const item of arr){const m=item.data(),own=m.senderId===me.uid;const node=el('article','msg'+(own?' own':''));node.append(el('div','msg-body',m.text));const meta=el('div','msg-meta');const d=m.createdAt?.toDate?.();meta.append(el('span',null,d?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Sending…'));if(own){const del=el('button','delete-msg','🗑');del.title='Delete message';del.onclick=async()=>{if(confirm('Delete this message?'))try{await deleteDoc(doc(db,'threads',id,'messages',item.id))}catch(e){status(e.message)}};meta.append(del)}node.append(meta);container.append(node)}container.scrollTop=container.scrollHeight;status('Private chat • latest 300 messages')},e=>status('Could not load messages: '+e.message))}
$('backToChats').onclick=()=>{$('appShell').classList.remove('chat-open')};
$('messageForm').onsubmit=async e=>{e.preventDefault();if(!active||!me)return;const text=clean($('messageInput').value);if(!text)return;const id=active.id;$('sendBtn').disabled=true;status('Sending…');try{await addDoc(collection(db,'threads',id,'messages'),{senderId:me.uid,text,createdAt:serverTimestamp()});$('messageInput').value='';status('Sent')}catch(err){status('Send failed: '+err.message)}finally{$('sendBtn').disabled=false}};
